### ISSUE TITLE
bad free variable error message

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#164]
consider

    with ufora.remotely:
        res = size([1,2,3])

we get the error message (due to the unresolved free variable `size`):

```
Traceback (most recent call last):
  File "parsing.py", line 32, in <module>
    with ufora.remotely:
  File "parsing.py", line 32, in <module>
    with ufora.remotely:
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 227, in trace
    globalsToSet = self.blockOperation(frame)
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 197, in blockOperation
    f_proxy = self.executor.define(withBlock).resultWithWakeup()
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 143, in define
    ).walkPyObject(obj)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 209, in walkPyObject
    self._registerWithBlock(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 433, in _registerWithBlock
    _convertUnresolvedFreeVariableExceptionAndRaise(e, sourceTree, pyObject.sourceFileName)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 57, in _convertUnresolvedFreeVariableExceptionAndRaise
    assert contextName is not None
AssertionError
```

@atzannes: why do we have `assert contextName is not None` in "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 57? We're not using that variable after the assert. Incidentally, the error message without the assert is totally reasonable:

```
Traceback (most recent call last):
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 227, in trace
    globalsToSet = self.blockOperation(frame)
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 197, in blockOperation
    f_proxy = self.executor.define(withBlock).resultWithWakeup()
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 148, in define
    raise Exceptions.PythonToForaConversionError(e.message, e.trace)
PythonToForaConversionError: unable to resolve free variable 'size' for pyfora conversion
  File "/home/tom/volumes/fora-playground/parsing.py", line 17
    res = size([1,2,3])

Traceback (most recent call last):
  File "parsing.py", line 16, in <module>
    with ufora.remotely:
  File "parsing.py", line 16, in <module>
    with ufora.remotely:
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 240, in trace
    raise err  
pyfora.Exceptions.PythonToForaConversionError: unable to resolve free variable 'size' for pyfora conversion
```

**Comment by tdp2110** [comment]
can't reproduce!

**Comment by atzannes** [comment]
Yeah that part of the code you pointed out seems it might be left-over code, I'll take a look and clean that up.
