### ISSUE TITLE
bad error message when converting unsupported code

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#169]
for example, if we haven't implemented a wrapper for scipy.special.beta, we'll get a stacktrace 

```
Traceback (most recent call last):
  File "Bla.py", line 621, in <module>
  ...
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 179, in submit
    futures = [self.define(fn)] + [self.define(arg) for arg in args]
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 143, in define
    ).walkPyObject(obj)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 225, in walkPyObject
    self._registerClassInstance(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 363, in _registerClassInstance
    classId = self.walkPyObject(classObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 221, in walkPyObject
    self._registerClass(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 491, in _registerClass
    classOrFunction=_ClassDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 534, in _classOrFunctionDefinition
    _, sourceLine = PyforaInspect.getsourcelines(pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyforaInspect.py", line 258, in getsourcelines
    lines, lnum = findsource(pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyforaInspect.py", line 174, in findsource
    raise IOError('could not find class definition')
IOError: could not find class definition
```

first of all PyforaInspect should say what it's failing on (error message doesn't mention beta)

**Comment by tdp2110** [comment]
a similar thing will happen if you try to convert an object which holds something unconvertable, for example an Executor.

two approaches @braxtonmckee mentions:
1. in our recursive `walkPyObject` function, we could insert debug info on the stack, or 
2. use exceptions and handle in stack unwinding using `try/except`

**Comment by tdp2110** [comment]
closing this issue, as it's a duplicate of #78
