### ISSUE TITLE
unhelpful error when importing a non-existent s3 bucket/key pair

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#180]
Running the following program

    import pyfora

    ufora = pyfora.connect('http://<manager-ip>:30000')
    raw_data = ufora.importS3Dataset('ufora-test-data',
                                  'DNE').result()

    with ufora.remotely:
        sz = len(raw_data)

    print 'sz = ', sz.toLocal().result()

blows up on the last line:

```
ERROR:root:Re-raising exception after amending lineno.
Traceback (most recent call last):
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 226, in trace
    globalsToSet = self.blockOperation(frame)
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 200, in blockOperation
    tuple_of_proxies = f_result_proxy.toTupleOfProxies().resultWithWakeup()
  File "/home/tom/volumes/src/packages/python/pyfora/Future.py", line 68, in resultWithWakeup
    return self.result(timeout=KEYBOARD_INTERRUPT_WAKEUP_INTERVAL)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 403, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 355, in __get_result
    raise type(self._exception), self._exception, self._traceback
PyforaError: Unknown error translating to dictionary of proxies: %s{u'responseType': 'Exception', u'message': 'Unknown exception. Guid = 59ef4921-2378-4d1f-8f99-48ed52067a09', u'messageId': 10}

Traceback (most recent call last):
  File "sz.py", line 16, in <module>
    sz = len(raw_data)
  File "sz.py", line 16, in <module>
    sz = len(raw_data)
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 226, in trace
    globalsToSet = self.blockOperation(frame)
  File "/home/tom/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 200, in blockOperation
    tuple_of_proxies = f_result_proxy.toTupleOfProxies().resultWithWakeup()
  File "/home/tom/volumes/src/packages/python/pyfora/Future.py", line 68, in resultWithWakeup
    return self.result(timeout=KEYBOARD_INTERRUPT_WAKEUP_INTERVAL)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 403, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 355, in __get_result
    raise type(self._exception), self._exception, self._traceback
pyfora.Exceptions.PyforaError: Unknown error translating to dictionary of proxies: %s{u'responseType': 'Exception', u'message': 'Unknown exception. Guid = 59ef4921-2378-4d1f-8f99-48ed52067a09', u'messageId': 10}
```

On the server, you can trace down the guid in ufora-gateway.log:

```
ERROR:root:547 > 2015-12-30 13:08:35,705 ERROR Exceptions.py:36@wrapException root - Invalid user exception encountered: GUID = b8ff906e-1b25-471e-912a-fab1aeefd07f
ERROR:root:547 > Location <class 'ufora.BackendGateway.SubscribableWebObjects.ObjectClassesToExpose.PyforaComputedValue.PyforaResultAsJson'>@139831154743344 doesn't have property result
ERROR:root:547 > Traceback (most recent call last):
ERROR:root:547 >   File "/opt/ufora/ufora/BackendGateway/SubscribableWebObjects/Subscriptions.py", line 105, in recomputeSubscription_
ERROR:root:547 >     newValue = self.subscriptionGetters[subscriptionId]()
ERROR:root:547 >   File "/opt/ufora/ufora/BackendGateway/SubscribableWebObjects/MessageProcessor.py", line 552, in <lambda>
ERROR:root:547 >     getValueFun = lambda: fieldFun(objectToRead)
ERROR:root:547 >   File "/opt/ufora/ufora/BackendGateway/SubscribableWebObjects/MessageProcessor.py", line 445, in getter
ERROR:root:547 >     return getattr(x, field)
ERROR:root:547 >   File "/opt/ufora/ufora/BackendGateway/ComputedGraph/ComputedGraph.py", line 117, in executeWithinTryBlock
ERROR:root:547 >     tr = func(arg)
ERROR:root:547 >   File "/opt/ufora/ufora/BackendGateway/SubscribableWebObjects/ObjectClassesToExpose/PyforaComputedValue.py", line 135, in jsonValueRepresentation
ERROR:root:547 >     return PyforaResultAsJson(computedValue=self, maxBytecount=None).result
ERROR:root:547 > UserWarning: Location <class 'ufora.BackendGateway.SubscribableWebObjects.ObjectClassesToExpose.PyforaComputedValue.PyforaResultAsJson'>@139831154743344 doesn't have property result
```

The problem is really that the bucket/key pair 'ufora-test-data', 'DNE' does not exist, but we don't see any problem until we go to use that dataset.

**Comment by tdp2110** [comment]
@braxtonmckee fixed this in b6624ed
