### ISSUE TITLE
can't use @property in with blocks

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#181]
consider the following Executor test case:

    def test_property_in_with_block(self):
        with self.create_executor() as fora:
            with fora.remotely:
                class C:
                    @property
                    def prop(self):
                        return 0

                res = C().prop

            self.assertEqual(res, 0)

This fails with:

```
======================================================================
ERROR: test_property_in_with_block (ufora.FORA.python.PurePython.WithBlockExecutor_test.WithBlockExecutors_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/volumes/src/ufora/FORA/python/PurePython/WithBlockExecutor_test.py", line 413, in test_property_in_with_block
    with fora.remotely:
  File "/volumes/src/ufora/FORA/python/PurePython/WithBlockExecutor_test.py", line 413, in test_property_in_with_block
    with fora.remotely:
  File "/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 226, in trace
    globalsToSet = self.blockOperation(frame)
  File "/volumes/src/packages/python/pyfora/WithBlockExecutor.py", line 196, in blockOperation
    f_proxy = self.executor.define(withBlock).resultWithWakeup()
  File "/volumes/src/packages/python/pyfora/Executor.py", line 170, in define
    ).walkPyObject(obj)
  File "/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 214, in walkPyObject
    self._registerWithBlock(objectId, pyObject)
  File "/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 447, in _registerWithBlock
    self.walkPyObject(resolution)
  File "/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 193, in walkPyObject
    pyObject
  File "/volumes/src/packages/python/pyfora/PureImplementationMappings.py", line 52, in mappableInstanceToPure
    return mapper.mapPythonInstanceToPyforaInstance(instance)
  File "/volumes/src/packages/python/pyfora/PureImplementationMapping.py", line 105, in mapPythonInstanceToPyforaInstance
    (instance.__name__ if hasattr(instance, "__name__") else instance))
PyforaNotImplementedError: conversion of 'property' not yet implemented

----------------------------------------------------------------------
Ran 1 test in 0.828s

FAILED (errors=1)
All test threads were properly cleaned up
```

**Comment by tdp2110** [comment]
we're seeing this as a free variable in the with block translation, but we don't have this problem if the class definition is outside the with block.

**Comment by tdp2110** [comment]
similarly, we can't use `__inline_fora` in a with block
