### ISSUE TITLE
socketIO exception

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#203]
using Tom's logistic regression script (ask him for it if you want to try), and other pyfora scripts, we've been hitting errors of the following form 

```
2016-02-10 20:52:05,714 computing in pyfora ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 232, in wait
    self._process_packets()
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/__init__.py", line 254, in _process_packets
    for engineIO_packet in self._transport.recv_packet():
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/transports.py", line 155, in recv_packet
    six.b(packet_text))
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/parsers.py", line 93, in parse_packet_text
    packet_type = int(get_character(packet_text, 0))
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/symmetries.py", line 17, in get_character
    return chr(get_byte(x, index))
  File "/usr/local/lib/python2.7/dist-packages/socketIO_client/symmetries.py", line 21, in get_byte
    return six.indexbytes(x, index)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 655, in indexbytes
    return ord(buf[i])
IndexError: string index out of range
```

**Comment by braxtonmckee** [comment]
I think the problem is in transports.py, line 145, the WebsocketTransport class is getting an empty string from _connection.recv(). I think a nasty but acceptable workaround would be to patch the function recv_packet to look like

```
    def recv_packet(self):
        try:
            packet_text = None
            while packet_text is None:
                packet_text = self._connection.recv()
        except websocket.WebSocketTimeoutException as e:
            raise TimeoutError('recv timed out (%s)' % e)
        except websocket.SSLError as e:
            raise ConnectionError('recv disconnected by SSL (%s)' % e)
        except websocket.WebSocketConnectionClosedException as e:
            raise ConnectionError('recv disconnected (%s)' % e)
        except socket.error as e:
            raise ConnectionError('recv disconnected (%s)' % e)
        engineIO_packet_type, engineIO_packet_data = parse_packet_text(
            six.b(packet_text))
        yield engineIO_packet_type, engineIO_packet_data
```

with the difference being that we're looping around the _connection.recv(), filtering out the empty strings.
