### ISSUE TITLE
free var lookup fails for default args

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#244]
Consider

    def test_default_arg_lookup(self):
        y = 2

        def g(x=y):
            return x + 1

        self.equivalentEvaluationTest(g)

This fails with

```======================================================================
ERROR: test_default_arg_lookup (ufora.FORA.python.PurePython.LocalExecutor_test.TestLocalExecutor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/volumes/src/ufora/FORA/python/PurePython/FunctionTestCases.py", line 399, in test_default_arg_lookup
    self.equivalentEvaluationTest(g)
  File "/volumes/src/ufora/FORA/python/PurePython/ExecutorTestCommon.py", line 76, in equivalentEvaluationTest
    func_proxy = executor.define(func).result()
  File "/volumes/src/packages/python/pyfora/Executor.py", line 183, in define
    raise Exceptions.PythonToForaConversionError(e.message, e.trace)
PythonToForaConversionError: unable to resolve free variable 'y' for pyfora conversion
  File "/volumes/src/ufora/FORA/python/PurePython/FunctionTestCases.py", line 396, in g
    def g(x=y):
  File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/volumes/src/ufora/FORA/python/PurePython/FunctionTestCases.py", line 399, in test_default_arg_lookup
    self.equivalentEvaluationTest(g)
  File "/volumes/src/ufora/FORA/python/PurePython/ExecutorTestCommon.py", line 76, in equivalentEvaluationTest
    func_proxy = executor.define(func).result()
  File "/volumes/src/packages/python/pyfora/Executor.py", line 183, in define
    raise Exceptions.PythonToForaConversionError(e.message, e.trace)

>> output captured in nose.ufora.FORA.python.PurePython.LocalExecutor_test.TestLocalExecutor.test_default_arg_lookup.1644.log <<

----------------------------------------------------------------------
```

**Comment by tdp2110** [comment]
The problem here is that any free variables coming from a default expression are not held by py function objects themselves. The _values_ of the default expressions, however, are held by the func object, for example with `f.func_defaults` or `f.__defaults__`.

When we convert functions, we should be inserting a placeholder variable which gets bound at function (or class) creation time, for example in converting `f()` from:

    def f():
        y = 2
        def g(x=(y,3)):
            pass
        return g

we should get

    let g = fun(x=x_default) { ... }; g

where x_default is bound "from the outside". Note this is different than if we had not def'd `g` yet, for example, in converting `f` itself, we could have

    let f = fun() {
        let y = 2;
        let x_default = (y, 3);
        let g = fun(x=x_default) { nothing };
        g
        };

Note that it's important that we evaluate the `x` default expression before the `g` expression, see #256.

Things get even trickier for class member functions, for example:

    def f():
        y = 2
        class C:
            def f(self, x=(y,3)): pass
        return C

Converting `f` should result in something like

    let f = fun() {
        let y = 2
        let x_default = (y, 3);
        let C = class {
            f: fun(x = x_default) { ... }
            };
        C
        };

but converting `f()` we should get 

    let C = class {
       f: fun(x = x_default) { ... }
       };
    C
    
where again we bind the value of `x_default` at actual object instantiation time.

**Comment by atzannes** [comment]
Looks like on the free variables analysis front we're doing the right thing (see commit above).

**Comment by tdp2110** [comment]
@atzannes yes, I agree. The point is, however, we don't resolve the values for any free vars in default args in the same way we get resolve values in the function body.
