### ISSUE TITLE
default args not evaluated at def time

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#256]
for example, this fails

    def test_default_args_err(self):
        def f():
            def g(x=1/0):
                return x
            return g(2)

        with self.create_executor() as executor:
            with self.assertRaises(ZeroDivisionError):
                with executor.remotely.downloadAll():
                    f()

with 

```
======================================================================
FAIL: test_default_args_err (ufora.FORA.python.PurePython.LocalExecutor_test.TestLocalExecutor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/volumes/src/ufora/FORA/python/PurePython/ExceptionTestCases.py", line 1072, in test_default_args_err
    f()
AssertionError: ZeroDivisionError not raised
  File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/volumes/src/ufora/FORA/python/PurePython/ExceptionTestCases.py", line 1072, in test_default_args_err
    f()
  File "/usr/local/lib/python2.7/unittest/case.py", line 116, in __exit__
    "{0} not raised".format(exc_name))

>> output captured in nose.ufora.FORA.python.PurePython.LocalExecutor_test.TestLocalExecutor.test_default_args_err.4258.log <<

----------------------------------------------------------------------
```

**Comment by tdp2110** [comment]
This seems like a lo-pri for now. Due to immutability, only way AFAIK this could matter is if the default expr throws an expression.
