### ISSUE TITLE
low-memory environments crash and don't give useful feedback

### ISSUE THREAD

**Issue by tdp2110** [ufora/ufora#267]
Say you run pyfora on a smallish* mac using our VM instructions. And say your VM doesn't have more than (I believe) 1 GB of memory. If you look at Setup.py line 140, you'll see that `self.cumulusMaxRamCacheMB` can be negative, which causes VectorDataManager.py to crash at line 49. Your server will then output

```
ufora-worker starting
Listening on 172.17.0.2 ports: 30009 and 30010
2016-05-25 14:29:47,563 INFO DynamicInliner.cppml:59    : STARTING DYNAMIC INLINING TASK!
Traceback (most recent call last):
  File "/opt/ufora/ufora/scripts/init/ufora-worker.py", line 142, in <module>
    main(createArgumentParser().parse_args())
  File "/opt/ufora/ufora/scripts/init/ufora-worker.py", line 120, in main
    worker = createService(args)
  File "/opt/ufora/ufora/scripts/init/ufora-worker.py", line 111, in createService
    objectStore=NullObjectStore.NullObjectStore()
  File "/opt/ufora/ufora/cumulus/distributed/CumulusService.py", line 119, in __init__
    self.cumulusMaxRamCacheSizeOverride
  File "/opt/ufora/ufora/FORA/VectorDataManager/VectorDataManager.py", line 49, in constructVDM
    VDM = FORANative.VectorDataManager(callbackScheduler, maxVectorChunkSize)
OverflowError: can't convert negative value to unsigned long
error: Forever detected script exited with code: 1
```

This is not very helpful to the user. If we really require a certain amount of memory, we could
  1. Give a better error message when setup fails
  2. at the very least, document this in our getting started page

* [how small? I'm not sure]

**Comment by opb** [comment]
I ran into this this morning. I'm on a Mac using the beta version of docker, where you you don't use docker-machine, docker just does it all for you locally... magically. Docker is configured to use 2GB, but I'm still hitting this problem.

```
[ 2016-05-27 06:35:54 | oliver@mbp ]  ( ~ )
508 $ docker run -d --name ufora -p 30000:30000 -v /Users/oliver/ufora:/var/ufora ufora/service
fcc3366bbba3c74ca0356aa0c4f53b38cb1ffb5436a71d2259508ac27e6ae847
[ 2016-05-27 06:36:02 | oliver@mbp ]  ( ~ )
509 $ tail -f ufora/logs/ufora-worker.log
    worker = createService(args)
  File "/opt/ufora/ufora/scripts/init/ufora-worker.py", line 111, in createService
    objectStore=NullObjectStore.NullObjectStore()
  File "/opt/ufora/ufora/cumulus/distributed/CumulusService.py", line 119, in __init__
    self.cumulusMaxRamCacheSizeOverride
  File "/opt/ufora/ufora/FORA/VectorDataManager/VectorDataManager.py", line 49, in constructVDM
    VDM = FORANative.VectorDataManager(callbackScheduler, maxVectorChunkSize)
OverflowError: can't convert negative value to unsigned long
error: Forever detected script exited with code: 1
error: Script restart attempt #1
```

**Comment by opb** [comment]
It worked when I increased it to 3GB.
