### ISSUE TITLE
Hard for user to tell how a given untranslatable value was reached

### ISSUE THREAD

**Issue by braxtonmckee** [ufora/ufora#78]
Try running the test 

    def test_typeWeCantTranslateYet(self):
        with self.create_executor() as fora:
            x = type(lambda x:x)
            with fora.remotely:
                y = x

The exception says 

```
PythonToForaConversionError: can't convert <type 'function'> (of type <type 'type'>) since we can't get its source code
```

But we cant tell what we're operating on.

**Comment by tdp2110** [comment]
as another example, 

or example, if we haven't implemented a wrapper for scipy.special.beta, we'll get a stacktrace

Traceback (most recent call last):
  File "Bla.py", line 621, in <module>
  ...
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 179, in submit
    futures = [self.define(fn)] + [self.define(arg) for arg in args]
  File "/home/tom/volumes/src/packages/python/pyfora/Executor.py", line 143, in define
    ).walkPyObject(obj)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 219, in walkPyObject
    self._registerFunction(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 472, in _registerFunction
    classOrFunction=_FunctionDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 556, in _classOrFunctionDefinition
    self.walkPyObject(resolution)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 225, in walkPyObject
    self._registerClassInstance(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 363, in _registerClassInstance
    classId = self.walkPyObject(classObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 221, in walkPyObject
    self._registerClass(objectId, pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 491, in _registerClass
    classOrFunction=_ClassDefinition
  File "/home/tom/volumes/src/packages/python/pyfora/PyObjectWalker.py", line 534, in _classOrFunctionDefinition
    _, sourceLine = PyforaInspect.getsourcelines(pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyforaInspect.py", line 258, in getsourcelines
    lines, lnum = findsource(pyObject)
  File "/home/tom/volumes/src/packages/python/pyfora/PyforaInspect.py", line 174, in findsource
    raise IOError('could not find class definition')
IOError: could not find class definition

**Comment by tdp2110** [comment]
a similar thing will happen if you try to convert an object which holds something unconvertable, for example an Executor.

two approaches @braxtonmckee mentions:
1. in our recursive walkPyObject function, we could insert debug info on the stack, or 
2. use exceptions and handle in stack unwinding using try/except

**Comment by tdp2110** [comment]
another option @braxtonmckee mentions is to introduce a "nonconvertible" symbol into the generated fora code, kind of like the pyforaUninitializedVariable thing. this moves the error to the runtime, which can then generate a stacktrace

**Comment by braxtonmckee** [comment]
This is in line with the way regular python programs behave: if you have a
variable that's undefined, you get an exception when you execute the code
that needs the variable. If that pathway is not touched by your program,
then you don't get an error. Pyfora should behave the same way: it's not an
error to reference untranslatable code if you don't actually execute it. In
particular, if you have a class which has methods with contain
untranslatable code, but you don't call those methods within code executing
in the Pyfora runtime, that should be OK.

On Thu, Jan 28, 2016 at 11:28 AM, Thomas Peters <notifications@github.com>
wrote:

> another option @braxtonmckee <https://github.com/braxtonmckee> mentions
> is to introduce a "nonconvertible" symbol into the generated fora code,
> kind of like the pyforaUninitializedVariable thing. this moves the error to
> the runtime, which can then generate a stacktrace
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufora/ufora/issues/78#issuecomment-176263714>.
>



-- 
-------------------------------------------------------------------------------------------
Braxton McKee                             CEO / Ufora
www.twitter.com/braxtonmckee       www.ufora.com

**Comment by tdp2110** [comment]
I've completed a first pass at this. There are a few related work-items to do, but I'll add issues for them as  I go.
